name: MiniGamePlugin
version: '${project.version}'
main: com.github.gavvydizzle.minigameplugin.MiniGamePlugin
api-version: '1.20'
authors: [GavvyDizzle]
description: Plugin containing multiple minigames
depend: [DecentHolograms, ProtocolLib, ServerUtils]
commands:
  minigame:
    aliases: [mg]
    description: MiniGame commands
    permission: minigameplugin.player